services:

  postgres:
    image: postgres:15
    container_name: crags_postgres
    environment:
      POSTGRES_USER: crags
      POSTGRES_PASSWORD: crags
      POSTGRES_DB: crags
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: