"""create compute systems table

Revision ID: 25c2237342f5
Revises: 
Create Date: 2026-03-04 14:23:06.378679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c2237342f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('system_type', sa.Enum('CPU', 'GPU', 'HYBRID', name='systemtype'), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('gpu_units', sa.Integer(), nullable=True),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OFFLINE', name='systemstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compute_systems')
    # ### end Alembic commands ###
