"""add bookings table

Revision ID: 3ec7eac7aa72
Revises: 6ebcde0851e2
Create Date: 2026-03-04 16:24:04.548529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec7eac7aa72'
down_revision: Union[str, Sequence[str], None] = '6ebcde0851e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_period', postgresql.TSRANGE(), nullable=True),
    sa.Column('req_cpu', sa.Integer(), nullable=True),
    sa.Column('req_gpu', sa.Integer(), nullable=True),
    sa.Column('req_ram', sa.Integer(), nullable=True),
    sa.Column('req_vram', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.Enum('FOREGROUND', 'BACKGROUND', name='accesstype'), nullable=True),
    sa.Column('academic_category', sa.String(), nullable=True),
    sa.Column('project_title', sa.String(), nullable=True),
    sa.Column('expected_deliverable', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'PREEMPTED', 'CANCELLED', 'COMPLETED', 'EXPIRED', name='bookingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['compute_systems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
